name: neural-varifold
channels:
  - conda-forge
  - pytorch
  - open3d-admin
dependencies:
- python==3.8
- pip
- numpy # pin version for conda
- scipy
- open3d
- pytorch==1.8.0 
- torchvision==0.9.0 
- torchaudio==0.8.0
- pip:
  - "torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+cu111.html"
  - "torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu111.html"
  - torch-geometric
  - https://data.pyg.org/whl/torch-1.8.0%2Bcu111/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl
  - https://data.pyg.org/whl/torch-1.8.0%2Bcu111/torch_spline_conv-1.2.1-cp38-cp38-linux_x86_64.whl
  - jax[cuda]
  - tensorflow
  - tensorflow-dataset
  - matplotlib