name: neural-varifold
channels:
  - conda-forge
  - pytorch
  - open3d-admin
dependencies:
- python==3.8
- pip
- numpy # pin version for conda
- scipy
- pip:
  - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
  - pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
  - torch-geometric
  - "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  - tensorflow
  - tensorflow-datasets
  - matplotlib
  - neural-tangent
  - trimesh
  - scikit-image
  - open3d